/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  color: {
    sun: {
      100: {
        key: '{color.sun.100}',
        $value: '#ffffff',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#FFFFFF',
          $type: 'color',
          key: '{color.sun.100}',
        },
        name: 'ColorSun100',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '100',
        },
        path: ['color', 'sun', '100'],
      },
      200: {
        key: '{color.sun.200}',
        $value: '#fcfcfb',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#FCFCFB',
          $type: 'color',
          key: '{color.sun.200}',
        },
        name: 'ColorSun200',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '200',
        },
        path: ['color', 'sun', '200'],
      },
      300: {
        key: '{color.sun.300}',
        $value: '#f7f6f4',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#F7F6F4',
          $type: 'color',
          key: '{color.sun.300}',
        },
        name: 'ColorSun300',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '300',
        },
        path: ['color', 'sun', '300'],
      },
      400: {
        key: '{color.sun.400}',
        $value: '#f1efea',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#F1EFEA',
          $type: 'color',
          key: '{color.sun.400}',
        },
        name: 'ColorSun400',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '400',
        },
        path: ['color', 'sun', '400'],
      },
      500: {
        key: '{color.sun.500}',
        $value: '#e9e6df',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#E9E6DF',
          $type: 'color',
          key: '{color.sun.500}',
        },
        name: 'ColorSun500',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '500',
        },
        path: ['color', 'sun', '500'],
      },
      600: {
        key: '{color.sun.600}',
        $value: '#d9d5cb',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#D9D5CB',
          $type: 'color',
          key: '{color.sun.600}',
        },
        name: 'ColorSun600',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '600',
        },
        path: ['color', 'sun', '600'],
      },
      700: {
        key: '{color.sun.700}',
        $value: '#c4bfb3',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#C4BFB3',
          $type: 'color',
          key: '{color.sun.700}',
        },
        name: 'ColorSun700',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '700',
        },
        path: ['color', 'sun', '700'],
      },
      800: {
        key: '{color.sun.800}',
        $value: '#a9a394',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#A9A394',
          $type: 'color',
          key: '{color.sun.800}',
        },
        name: 'ColorSun800',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '800',
        },
        path: ['color', 'sun', '800'],
      },
      900: {
        key: '{color.sun.900}',
        $value: '#8c8576',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#8C8576',
          $type: 'color',
          key: '{color.sun.900}',
        },
        name: 'ColorSun900',
        attributes: {
          category: 'color',
          type: 'sun',
          item: '900',
        },
        path: ['color', 'sun', '900'],
      },
    },
    moon: {
      100: {
        key: '{color.moon.100}',
        $value: '#f4f5f6',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#F4F5F6',
          $type: 'color',
          key: '{color.moon.100}',
        },
        name: 'ColorMoon100',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '100',
        },
        path: ['color', 'moon', '100'],
      },
      200: {
        key: '{color.moon.200}',
        $value: '#e1e3e6',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#E1E3E6',
          $type: 'color',
          key: '{color.moon.200}',
        },
        name: 'ColorMoon200',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '200',
        },
        path: ['color', 'moon', '200'],
      },
      300: {
        key: '{color.moon.300}',
        $value: '#c6cad0',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#C6CAD0',
          $type: 'color',
          key: '{color.moon.300}',
        },
        name: 'ColorMoon300',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '300',
        },
        path: ['color', 'moon', '300'],
      },
      400: {
        key: '{color.moon.400}',
        $value: '#9aa1aa',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#9AA1AA',
          $type: 'color',
          key: '{color.moon.400}',
        },
        name: 'ColorMoon400',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '400',
        },
        path: ['color', 'moon', '400'],
      },
      500: {
        key: '{color.moon.500}',
        $value: '#6b7280',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#6B7280',
          $type: 'color',
          key: '{color.moon.500}',
        },
        name: 'ColorMoon500',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '500',
        },
        path: ['color', 'moon', '500'],
      },
      600: {
        key: '{color.moon.600}',
        $value: '#4b5563',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#4B5563',
          $type: 'color',
          key: '{color.moon.600}',
        },
        name: 'ColorMoon600',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '600',
        },
        path: ['color', 'moon', '600'],
      },
      700: {
        key: '{color.moon.700}',
        $value: '#374151',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#374151',
          $type: 'color',
          key: '{color.moon.700}',
        },
        name: 'ColorMoon700',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '700',
        },
        path: ['color', 'moon', '700'],
      },
      800: {
        key: '{color.moon.800}',
        $value: '#1f2937',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#1F2937',
          $type: 'color',
          key: '{color.moon.800}',
        },
        name: 'ColorMoon800',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '800',
        },
        path: ['color', 'moon', '800'],
      },
      900: {
        key: '{color.moon.900}',
        $value: '#111827',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#111827',
          $type: 'color',
          key: '{color.moon.900}',
        },
        name: 'ColorMoon900',
        attributes: {
          category: 'color',
          type: 'moon',
          item: '900',
        },
        path: ['color', 'moon', '900'],
      },
    },
    star: {
      100: {
        key: '{color.star.100}',
        $value: '#fff1ee',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#FFF1EE',
          $type: 'color',
          key: '{color.star.100}',
        },
        name: 'ColorStar100',
        attributes: {
          category: 'color',
          type: 'star',
          item: '100',
        },
        path: ['color', 'star', '100'],
      },
      200: {
        key: '{color.star.200}',
        $value: '#ffdad3',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#FFDAD3',
          $type: 'color',
          key: '{color.star.200}',
        },
        name: 'ColorStar200',
        attributes: {
          category: 'color',
          type: 'star',
          item: '200',
        },
        path: ['color', 'star', '200'],
      },
      300: {
        key: '{color.star.300}',
        $value: '#ffb8a8',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#FFB8A8',
          $type: 'color',
          key: '{color.star.300}',
        },
        name: 'ColorStar300',
        attributes: {
          category: 'color',
          type: 'star',
          item: '300',
        },
        path: ['color', 'star', '300'],
      },
      400: {
        key: '{color.star.400}',
        $value: '#ff8f78',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#FF8F78',
          $type: 'color',
          key: '{color.star.400}',
        },
        name: 'ColorStar400',
        attributes: {
          category: 'color',
          type: 'star',
          item: '400',
        },
        path: ['color', 'star', '400'],
      },
      500: {
        key: '{color.star.500}',
        $value: '#f76b4d',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#F76B4D',
          $type: 'color',
          key: '{color.star.500}',
        },
        name: 'ColorStar500',
        attributes: {
          category: 'color',
          type: 'star',
          item: '500',
        },
        path: ['color', 'star', '500'],
      },
      600: {
        key: '{color.star.600}',
        $value: '#d9573e',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#D9573E',
          $type: 'color',
          key: '{color.star.600}',
        },
        name: 'ColorStar600',
        attributes: {
          category: 'color',
          type: 'star',
          item: '600',
        },
        path: ['color', 'star', '600'],
      },
      700: {
        key: '{color.star.700}',
        $value: '#b84532',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#B84532',
          $type: 'color',
          key: '{color.star.700}',
        },
        name: 'ColorStar700',
        attributes: {
          category: 'color',
          type: 'star',
          item: '700',
        },
        path: ['color', 'star', '700'],
      },
      800: {
        key: '{color.star.800}',
        $value: '#933429',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#933429',
          $type: 'color',
          key: '{color.star.800}',
        },
        name: 'ColorStar800',
        attributes: {
          category: 'color',
          type: 'star',
          item: '800',
        },
        path: ['color', 'star', '800'],
      },
      900: {
        key: '{color.star.900}',
        $value: '#6f251d',
        filePath: 'src/design-tokens/colors.json',
        isSource: true,
        $type: 'color',
        original: {
          $value: '#6F251D',
          $type: 'color',
          key: '{color.star.900}',
        },
        name: 'ColorStar900',
        attributes: {
          category: 'color',
          type: 'star',
          item: '900',
        },
        path: ['color', 'star', '900'],
      },
    },
  },
  font: {
    family: {
      1: {
        key: '{font.family.1}',
        $type: 'fontFamily',
        $value: [
          'Forum',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'serif',
        ],
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'fontFamily',
          $value: [
            'Forum',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'serif',
          ],
          key: '{font.family.1}',
        },
        name: 'FontFamily1',
        attributes: {
          category: 'font',
          type: 'family',
          item: '1',
        },
        path: ['font', 'family', '1'],
      },
      2: {
        key: '{font.family.2}',
        $type: 'fontFamily',
        $value: [
          'Outfit',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'fontFamily',
          $value: [
            'Outfit',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'sans-serif',
          ],
          key: '{font.family.2}',
        },
        name: 'FontFamily2',
        attributes: {
          category: 'font',
          type: 'family',
          item: '2',
        },
        path: ['font', 'family', '2'],
      },
    },
    size: {
      1: {
        key: '{font.size.1}',
        $type: 'dimension',
        $value: '14px',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '14px',
          key: '{font.size.1}',
        },
        name: 'FontSize1',
        attributes: {
          category: 'font',
          type: 'size',
          item: '1',
        },
        path: ['font', 'size', '1'],
      },
      2: {
        key: '{font.size.2}',
        $type: 'dimension',
        $value: '18px',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '{font.size.base}',
          key: '{font.size.2}',
        },
        name: 'FontSize2',
        attributes: {
          category: 'font',
          type: 'size',
          item: '2',
        },
        path: ['font', 'size', '2'],
      },
      3: {
        key: '{font.size.3}',
        $type: 'dimension',
        $value: '24px',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '24px',
          key: '{font.size.3}',
        },
        name: 'FontSize3',
        attributes: {
          category: 'font',
          type: 'size',
          item: '3',
        },
        path: ['font', 'size', '3'],
      },
      4: {
        key: '{font.size.4}',
        $type: 'dimension',
        $value: '32px',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '32px',
          key: '{font.size.4}',
        },
        name: 'FontSize4',
        attributes: {
          category: 'font',
          type: 'size',
          item: '4',
        },
        path: ['font', 'size', '4'],
      },
      5: {
        key: '{font.size.5}',
        $type: 'dimension',
        $value: 'clamp(1rem, min(20vmin, 10vw), 10rem)',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: 'clamp(1rem, min(20vmin, 10vw), 10rem)',
          key: '{font.size.5}',
        },
        name: 'FontSize5',
        attributes: {
          category: 'font',
          type: 'size',
          item: '5',
        },
        path: ['font', 'size', '5'],
      },
      base: {
        key: '{font.size.base}',
        $type: 'dimension',
        $value: '18px',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '18px',
          key: '{font.size.base}',
        },
        name: 'FontSizeBase',
        attributes: {
          category: 'font',
          type: 'size',
          item: 'base',
        },
        path: ['font', 'size', 'base'],
      },
    },
    'line-height': {
      1: {
        key: '{font.line-height.1}',
        $value: 1.5,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $value: 1.5,
          key: '{font.line-height.1}',
        },
        name: 'FontLineHeight1',
        attributes: {
          category: 'font',
          type: 'line-height',
          item: '1',
        },
        path: ['font', 'line-height', '1'],
      },
      2: {
        key: '{font.line-height.2}',
        $value: 1.75,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $value: 1.75,
          key: '{font.line-height.2}',
        },
        name: 'FontLineHeight2',
        attributes: {
          category: 'font',
          type: 'line-height',
          item: '2',
        },
        path: ['font', 'line-height', '2'],
      },
      3: {
        key: '{font.line-height.3}',
        $value: 1.25,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $value: 1.25,
          key: '{font.line-height.3}',
        },
        name: 'FontLineHeight3',
        attributes: {
          category: 'font',
          type: 'line-height',
          item: '3',
        },
        path: ['font', 'line-height', '3'],
      },
      4: {
        key: '{font.line-height.4}',
        $value: 1.1,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $value: 1.1,
          key: '{font.line-height.4}',
        },
        name: 'FontLineHeight4',
        attributes: {
          category: 'font',
          type: 'line-height',
          item: '4',
        },
        path: ['font', 'line-height', '4'],
      },
      5: {
        key: '{font.line-height.5}',
        $value: 0.875,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $value: 0.875,
          key: '{font.line-height.5}',
        },
        name: 'FontLineHeight5',
        attributes: {
          category: 'font',
          type: 'line-height',
          item: '5',
        },
        path: ['font', 'line-height', '5'],
      },
    },
    'letter-spacing': {
      1: {
        key: '{font.letter-spacing.1}',
        $type: 'dimension',
        $value: '0',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '0',
          key: '{font.letter-spacing.1}',
        },
        name: 'FontLetterSpacing1',
        attributes: {
          category: 'font',
          type: 'letter-spacing',
          item: '1',
        },
        path: ['font', 'letter-spacing', '1'],
      },
      2: {
        key: '{font.letter-spacing.2}',
        $type: 'dimension',
        $value: '1px',
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'dimension',
          $value: '1px',
          key: '{font.letter-spacing.2}',
        },
        name: 'FontLetterSpacing2',
        attributes: {
          category: 'font',
          type: 'letter-spacing',
          item: '2',
        },
        path: ['font', 'letter-spacing', '2'],
      },
    },
    weight: {
      1: {
        key: '{font.weight.1}',
        $type: 'fontWeight',
        $value: 400,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'fontWeight',
          $value: 400,
          key: '{font.weight.1}',
        },
        name: 'FontWeight1',
        attributes: {
          category: 'font',
          type: 'weight',
          item: '1',
        },
        path: ['font', 'weight', '1'],
      },
      2: {
        key: '{font.weight.2}',
        $type: 'fontWeight',
        $value: 700,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'fontWeight',
          $value: 700,
          key: '{font.weight.2}',
        },
        name: 'FontWeight2',
        attributes: {
          category: 'font',
          type: 'weight',
          item: '2',
        },
        path: ['font', 'weight', '2'],
      },
      3: {
        key: '{font.weight.3}',
        $type: 'fontWeight',
        $value: 300,
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        original: {
          $type: 'fontWeight',
          $value: 300,
          key: '{font.weight.3}',
        },
        name: 'FontWeight3',
        attributes: {
          category: 'font',
          type: 'weight',
          item: '3',
        },
        path: ['font', 'weight', '3'],
      },
    },
    title: {
      1: {
        key: '{font.title.1}',
        $value: {
          fontFamily: [
            'Forum',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'serif',
          ],
          fontWeight: 400,
          fontSize: 'clamp(1rem, min(20vmin, 10vw), 10rem)',
          lineHeight: 0.875,
        },
        $extensions: {
          $targetElement: 'h1',
          $name: 'Title 1',
        },
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        $type: 'typography',
        original: {
          $value: {
            fontFamily: '{font.family.1}',
            fontWeight: '{font.weight.1}',
            fontSize: '{font.size.5}',
            lineHeight: '{font.line-height.5}',
          },
          $extensions: {
            $targetElement: 'h1',
            $name: 'Title 1',
          },
          $type: 'typography',
          key: '{font.title.1}',
        },
        name: 'FontTitle1',
        attributes: {
          category: 'font',
          type: 'title',
          item: '1',
        },
        path: ['font', 'title', '1'],
      },
      2: {
        key: '{font.title.2}',
        $value: {
          fontFamily: [
            'Outfit',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'sans-serif',
          ],
          fontWeight: 400,
          fontSize: '32px',
          lineHeight: 1.1,
        },
        $extensions: {
          $targetElement: 'h2',
        },
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        $type: 'typography',
        original: {
          $value: {
            fontFamily: '{font.family.2}',
            fontWeight: '{font.weight.1}',
            fontSize: '{font.size.4}',
            lineHeight: '{font.line-height.4}',
          },
          $extensions: {
            $targetElement: 'h2',
          },
          $type: 'typography',
          key: '{font.title.2}',
        },
        name: 'FontTitle2',
        attributes: {
          category: 'font',
          type: 'title',
          item: '2',
        },
        path: ['font', 'title', '2'],
      },
      3: {
        key: '{font.title.3}',
        $value: {
          fontFamily: [
            'Outfit',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'sans-serif',
          ],
          fontWeight: 300,
          fontSize: '32px',
          lineHeight: 1.1,
        },
        $extensions: {
          $targetElement: 'h3',
        },
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        $type: 'typography',
        original: {
          $value: {
            fontFamily: '{font.family.2}',
            fontWeight: '{font.weight.3}',
            fontSize: '{font.size.4}',
            lineHeight: '{font.line-height.4}',
          },
          $extensions: {
            $targetElement: 'h3',
          },
          $type: 'typography',
          key: '{font.title.3}',
        },
        name: 'FontTitle3',
        attributes: {
          category: 'font',
          type: 'title',
          item: '3',
        },
        path: ['font', 'title', '3'],
      },
    },
    body: {
      1: {
        key: '{font.body.1}',
        $value: {
          fontFamily: [
            'Outfit',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'sans-serif',
          ],
          fontWeight: 400,
          fontSize: '18px',
          lineHeight: 1.5,
        },
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        $type: 'typography',
        original: {
          $value: {
            fontFamily: '{font.family.2}',
            fontWeight: '{font.weight.1}',
            fontSize: '{font.size.2}',
            lineHeight: '{font.line-height.1}',
          },
          $type: 'typography',
          key: '{font.body.1}',
        },
        name: 'FontBody1',
        attributes: {
          category: 'font',
          type: 'body',
          item: '1',
        },
        path: ['font', 'body', '1'],
      },
      2: {
        key: '{font.body.2}',
        $value: {
          fontFamily: [
            'Outfit',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'sans-serif',
          ],
          fontWeight: 300,
          fontSize: '24px',
          lineHeight: 1.5,
        },
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        $type: 'typography',
        original: {
          $value: {
            fontFamily: '{font.family.2}',
            fontWeight: '{font.weight.3}',
            fontSize: '{font.size.3}',
            lineHeight: '{font.line-height.1}',
          },
          $type: 'typography',
          key: '{font.body.2}',
        },
        name: 'FontBody2',
        attributes: {
          category: 'font',
          type: 'body',
          item: '2',
        },
        path: ['font', 'body', '2'],
      },
    },
    button: {
      1: {
        key: '{font.button.1}',
        $value: {
          fontFamily: [
            'Forum',
            'system-ui',
            '-apple-system',
            'Segoe UI',
            'Helvetica Neue',
            'Arial',
            'serif',
          ],
          fontWeight: 400,
          fontSize: '18px',
          lineHeight: 1.5,
        },
        filePath: 'src/design-tokens/font.json',
        isSource: true,
        $type: 'typography',
        original: {
          $value: {
            fontFamily: '{font.family.1}',
            fontWeight: '{font.weight.1}',
            fontSize: '{font.size.2}',
            lineHeight: '{font.line-height.1}',
          },
          $type: 'typography',
          key: '{font.button.1}',
        },
        name: 'FontButton1',
        attributes: {
          category: 'font',
          type: 'button',
          item: '1',
        },
        path: ['font', 'button', '1'],
      },
    },
  },
  spacing: {
    0: {
      key: '{spacing.0}',
      $value: '0px',
      $extensions: {
        semantic: '0',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '0px',
        $extensions: {
          semantic: '0',
        },
        $type: 'dimension',
        key: '{spacing.0}',
      },
      name: 'Spacing0',
      attributes: {
        category: 'spacing',
        type: '0',
      },
      path: ['spacing', '0'],
    },
    1: {
      key: '{spacing.1}',
      $value: '4px',
      $extensions: {
        semantic: '2xs',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '4px',
        $extensions: {
          semantic: '2xs',
        },
        $type: 'dimension',
        key: '{spacing.1}',
      },
      name: 'Spacing1',
      attributes: {
        category: 'spacing',
        type: '1',
      },
      path: ['spacing', '1'],
    },
    2: {
      key: '{spacing.2}',
      $value: '8px',
      $extensions: {
        semantic: 'xs',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '8px',
        $extensions: {
          semantic: 'xs',
        },
        $type: 'dimension',
        key: '{spacing.2}',
      },
      name: 'Spacing2',
      attributes: {
        category: 'spacing',
        type: '2',
      },
      path: ['spacing', '2'],
    },
    3: {
      key: '{spacing.3}',
      $value: '12px',
      $extensions: {
        semantic: 'sm',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '12px',
        $extensions: {
          semantic: 'sm',
        },
        $type: 'dimension',
        key: '{spacing.3}',
      },
      name: 'Spacing3',
      attributes: {
        category: 'spacing',
        type: '3',
      },
      path: ['spacing', '3'],
    },
    4: {
      key: '{spacing.4}',
      $value: '16px',
      $extensions: {
        semantic: 'md',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '16px',
        $extensions: {
          semantic: 'md',
        },
        $type: 'dimension',
        key: '{spacing.4}',
      },
      name: 'Spacing4',
      attributes: {
        category: 'spacing',
        type: '4',
      },
      path: ['spacing', '4'],
    },
    5: {
      key: '{spacing.5}',
      $value: '24px',
      $extensions: {
        semantic: 'lg',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '24px',
        $extensions: {
          semantic: 'lg',
        },
        $type: 'dimension',
        key: '{spacing.5}',
      },
      name: 'Spacing5',
      attributes: {
        category: 'spacing',
        type: '5',
      },
      path: ['spacing', '5'],
    },
    6: {
      key: '{spacing.6}',
      $value: '32px',
      $extensions: {
        semantic: 'xl',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '32px',
        $extensions: {
          semantic: 'xl',
        },
        $type: 'dimension',
        key: '{spacing.6}',
      },
      name: 'Spacing6',
      attributes: {
        category: 'spacing',
        type: '6',
      },
      path: ['spacing', '6'],
    },
    7: {
      key: '{spacing.7}',
      $value: '56px',
      $extensions: {
        semantic: '2xl',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '56px',
        $extensions: {
          semantic: '2xl',
        },
        $type: 'dimension',
        key: '{spacing.7}',
      },
      name: 'Spacing7',
      attributes: {
        category: 'spacing',
        type: '7',
      },
      path: ['spacing', '7'],
    },
    8: {
      key: '{spacing.8}',
      $value: '72px',
      $extensions: {
        semantic: '3xl',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '72px',
        $extensions: {
          semantic: '3xl',
        },
        $type: 'dimension',
        key: '{spacing.8}',
      },
      name: 'Spacing8',
      attributes: {
        category: 'spacing',
        type: '8',
      },
      path: ['spacing', '8'],
    },
    9: {
      key: '{spacing.9}',
      $value: '96px',
      $extensions: {
        semantic: '4xl',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '96px',
        $extensions: {
          semantic: '4xl',
        },
        $type: 'dimension',
        key: '{spacing.9}',
      },
      name: 'Spacing9',
      attributes: {
        category: 'spacing',
        type: '9',
      },
      path: ['spacing', '9'],
    },
    10: {
      key: '{spacing.10}',
      $value: '120px',
      $extensions: {
        semantic: '5xl',
      },
      filePath: 'src/design-tokens/spacing.json',
      isSource: true,
      $type: 'dimension',
      original: {
        $value: '120px',
        $extensions: {
          semantic: '5xl',
        },
        $type: 'dimension',
        key: '{spacing.10}',
      },
      name: 'Spacing10',
      attributes: {
        category: 'spacing',
        type: '10',
      },
      path: ['spacing', '10'],
    },
  },
};
